package midplay.util;

// GENERATED BY build_lang.mjs. DO NOT EDIT.

import java.util.Hashtable;

public class Lang {
  private static String c = "en";
  private static Hashtable d;
  private static boolean i = false;

  private static final String[] KEYS = {
    "lang", "action.back", "action.cancel", "action.exit", "action.ok", "action.save", "app.name", "confirm.exit", "confirm.discard_changes", "favorites.add",
    "favorites.error.remove_failed", "favorites.error.save_failed", "favorites.remove", "favorites.status.added", "favorites.status.already_exists", "favorites.status.removed", "files.empty", "files.not_audio", "files.root", "language.en",
    "language.tr", "language.vi", "language.he", "language.pl", "language.pt", "media.album", "media.playlist", "media.track", "menu.discover_playlists", "menu.favorites",
    "menu.now_playing", "menu.recent", "menu.downloads", "menu.files", "menu.reorder", "menu.search", "menu.settings", "menu.about", "menu.visibility", "menu.equalizer",
    "player.next", "player.play", "player.previous", "player.repeat", "player.show_playlist", "player.shuffle", "player.status.loading", "player.status.paused", "player.status.playing", "player.status.starting",
    "player.status.stopped", "player.status.stopping", "player.status.finished", "player.status.ready", "player.status.repeat_all", "player.status.repeat_one", "player.status.repeat_off", "player.status.shuffle_on", "player.status.shuffle_off", "player.stop",
    "player.volume", "details.title", "details.name", "details.type", "details.custom", "details.system", "details.track_count", "details.artist", "details.duration", "details.url",
    "details.unknown_artist", "details.unknown_duration", "details.no_url", "download.action", "download.downloading", "download.completed", "download.already_downloaded", "download.in_progress", "download.error", "download.play",
    "download.delete", "download.delete_all", "download.refresh", "download.link", "download.link_url", "download.link_thumb", "download.link_name", "download.link_artist", "download.link_no_files", "download.link_error_url",
    "download.link_error", "download.link_status", "download.link_manual", "download.status.deleted", "download.status.cleared", "download.confirm.clear", "cache.listen", "cache.delete", "cache.delete_all", "cache.title",
    "cache.unknown", "cache.status.removed", "cache.status.cleared", "cache.confirm.delete_all", "playlist.add_track", "playlist.create", "playlist.confirm.delete_with_tracks", "playlist.view_tracks", "playlist.error.add_track_failed", "playlist.error.track_already_exists",
    "playlist.error.cannot_rename_system", "playlist.error.create_failed", "playlist.error.empty_name", "playlist.error.remove_track_failed", "playlist.error.rename_failed", "playlist.name", "playlist.rename", "playlist.select", "playlist.status.created", "playlist.status.no_custom",
    "playlist.status.renamed", "playlist.status.track_added", "playlist.status.track_removed", "queue.add_to_queue", "queue.add_all_to_queue", "queue.added", "queue.sort", "queue.save_as_playlist", "recent.clear", "recent.confirm.clear",
    "recent.status.cleared", "search.error.empty_keyword", "search.placeholder", "search.results", "search.status.no_results", "search.status.searching", "search.type", "session.resume_prompt", "settings.audio_quality", "settings.auto_update",
    "settings.check_update", "settings.save_last_session", "settings.options", "settings.theme_mode", "settings.theme_color", "settings.use_wifi", "settings.load_thumbnails", "settings.theme_mode_options.dark", "settings.theme_mode_options.light", "settings.player_method",
    "settings.player_method_options.pass_inputstream", "settings.player_method_options.pass_url", "settings.download_path", "settings.error.save_failed", "settings.error.save_theme", "settings.error.load_theme", "settings.error.color_update_failed", "settings.language", "settings.reorder.instructions", "settings.reorder.saved",
    "settings.service", "settings.status.saved", "settings.visibility.instructions", "settings.visibility.saved", "status.error", "status.loading", "status.load_more", "status.no_data", "status.no_updates", "status.update_available",
    "time.error.invalid_duration", "time.error.invalid_format", "time.minutes", "timer.action", "timer.actions.exit_app", "timer.actions.stop_playback", "timer.cancel", "timer.confirm.exit", "timer.set", "timer.sleep_timer",
    "timer.status.cancelled", "timer.status.expired", "timer.status.set", "eq.enable", "eq.presets", "eq.manual", "eq.band", "eq.not_supported"
  };

  private static final String[] EN_VALS = {
    "en", "Back", "Cancel", "Exit", "OK",
    "Save", "MIDPlay", "Are you sure you want to exit?", "Discard unsaved changes?", "Add to Favorites",
    "Failed to remove favorite", "Failed to save favorite", "Remove from Favorites", "Added to favorites", "Already in favorites",
    "Removed from favorites", "No files in this folder", "Not an audio file", "Go to root", "English",
    "Türkçe", "Tiếng Việt", "עברית", "Polski", "Português (Brasil)",
    "Album", "Playlist", "Track", "Discover Playlists", "Favorites",
    "Now Playing", "Recent", "Downloads", "File Explorer", "Reorder Menu",
    "Search", "Settings", "About", "Menu Visibility", "Equalizer",
    "Next", "Play", "Previous", "Repeat", "Show Playlist",
    "Shuffle", "Loading...", "Paused", "Playing...", "Starting...",
    "Stopped", "Stopping...", "Finished", "Ready", "Playlist repeat enabled",
    "Track repeat enabled", "Repeat disabled", "Playlist shuffle enabled", "Playlist shuffle disabled", "Stop",
    "Volume", "Details", "Name", "Type", "Custom",
    "System", "Track Count", "Artist", "Duration", "URL",
    "Unknown Artist", "Unknown Duration", "No URL", "Download", "Downloading...",
    "Download completed", "Song already downloaded", "Download already in progress", "Download failed: {0}", "Play",
    "Delete", "Delete All", "Refresh", "Link Local File", "Track URL",
    "Thumbnail URL", "Track Name", "Artist", "No local files found in the download folder", "Enter the track URL",
    "Could not link this file", "File linked successfully", "Enter URL manually", "Download deleted", "All downloads cleared",
    "Delete all downloaded songs?", "Listen", "Delete", "Delete All", "Cached Songs",
    "Unknown Song", "Cached song removed", "Cache cleared", "Delete all cached songs?", "Add to Playlist",
    "Create Playlist", "This playlist is not empty. Delete all?", "View Track List", "Failed to add track to playlist", "Track already exists in playlist",
    "Cannot rename system playlists", "Failed to create playlist", "Playlist name cannot be empty", "Failed to remove track from playlist", "Failed to rename playlist",
    "Playlist Name", "Rename Playlist", "Select Playlist", "Playlist created successfully", "No custom playlists available",
    "Playlist renamed successfully", "Track added to playlist successfully", "Track removed from playlist successfully", "Add to Queue", "Add All to Queue",
    "Added to queue", "Sort Queue", "Save as Playlist", "Clear History", "Clear all recent items?",
    "History cleared", "Please enter a keyword to search", "Enter keywords to search...", "Search Results", "No results found",
    "Searching for: {0}", "Search Type", "Resume your last session?", "Audio Quality", "Automatic Updates",
    "Check for Updates", "Save Last Session", "Options", "Appearance", "Theme Color",
    "Use Wi-Fi (Blackberry)", "Load Thumbnails", "Dark", "Light", "Player Method",
    "Pass InputStream", "Pass URL", "Download Path", "Failed to save settings", "Error saving theme: {0}",
    "Error loading theme: {0}", "Theme color update failed. Theme mode was saved.", "Language", "Select an item to move, then select the destination position", "Order saved",
    "Service", "Settings saved successfully", "Select items to hide/show. [x] = show, [] = hide", "Visibility settings saved", "An error occurred",
    "Loading...", "Load more...", "No data available!", "No updates available. You have the latest version", "New version available. Update now?",
    "Duration must be 1-999 minutes", "Invalid time format", "Minutes", "Timer Action", "Exit Application",
    "Stop Playback", "Cancel Timer", "Timer will exit the application when expired. Continue?", "Set Timer", "Sleep Timer",
    "Sleep timer cancelled", "Sleep timer expired", "Sleep timer activated", "Enable", "Presets",
    "Manual", "Band", "Equalizer is not supported on this device"
  };

  private static final String[] HE_VALS = {
    "he", "חזור", "ביטול", "יציאה", "אישור",
    "שמור", "MIDPlay", "אתה בטוח שאתה רוצה לצאת?", "לבטל שינויים שלא נשמרו?", "הוסף למועדפים",
    "המחיקה מהמועדפים נכשלה", "שמירת המועדפים נכשלה", "מחק מהמועדפים", "נוסף למועדפים", "כבר נמצא במועדפים",
    "נמחק מהמועדפים", "אין קבצים בתיקייה זו", "לא קובץ שמע", "עבור לתיקיית הבסיס", "English",
    "Türkçe", "Tiếng Việt", "עברית", "Polski", "Português (Brasil)",
    "אלבום", "רשימת השמעה", "רצועה", "גלה רשימות השמעה", "מועדפים",
    "מושמע כעת", "אחרונים", "הורדות", "סייר קבצים", "סדר תפריט",
    "חיפוש", "הגדרות", "אודות", "נראות התפריט", "אקולייזר",
    "הבא", "נגן", "הקודם", "חזרה", "הצג רשימת השמעה",
    "ערבוב", "טוען...", "בהשהייה", "מושמע כעת...", "מתחיל...",
    "מופסק", "עוצר...", "סיים", "מוכן", "חזרה על רשימת ההשמעה הופעלה",
    "חזרה על השיר הופעלה", "החזרה כבויה", "ערבוב רשימת ההשמעה הופעל", "ערבוב רשימת ההשמעה כובה", "עצור",
    "עוצמת שמע", "פרטים", "שם", "סוג", "מותאם אישית",
    "מערכת", "מספר רצועות", "אמן", "משך זמן", "כתובת URL",
    "אמן לא ידוע", "משך זמן לא ידוע", "אין כתובת URL", "הורדה", "מוריד...",
    "ההורדה הושלמה", "השיר כבר הורד", "ההורדה כבר מתבצעת", "ההורדה נכשלה: {0}", "נגן",
    "מחק", "מחק הכל", "Refresh", "קשור קובץ מקומי", "כתובת URL של הרצועה",
    "כתובת URL של התמונה הממוזערת", "שם הרצועה", "אמן", "לא נמצאו קבצים מקומיים בתיקיית ההורדות", "נא להזין את כתובת ה-URL של הרצועה",
    "לא ניתן היה לקשר קובץ זה", "הקובץ קושר בהצלחה", "הזן כתובת URL ידנית", "ההורדה נמחקה", "כל ההורדות נמחקו",
    "למחוק את כל השירים שהורדו?", "Listen", "Delete", "Delete All", "Cached Songs",
    "Unknown Song", "Cached song removed", "Cache cleared", "Delete all cached songs?", "הוסף לרשימת השמעה",
    "צור רשימת השמעה", "רשימת ההשמעה הזו מכילה שירים. למחוק את רשימת ההשמעה ואת כל השירים?", "הצג רשימת רצועות", "הוספת הרצועה לרשימת ההשמעה נכשלה", "הרצועה כבר נמצאת ברשימת ההשמעה",
    "לא ניתן לשנות את השם של רשימת השמעה של המערכת", "נכשל ביצירת רשימת השמעה", "שם רשימת ההשמעה לא יכול להיות ריק", "מחיקת הרצועה מרשימת ההשמעה נכשל", "שינוי השם של רשימת ההשמעה נכשל",
    "שם רשימת השמעה", "שנה שם רשימת השמעה", "בחר רשימת השמעה", "רשימת השמעה נוצרה בהצלחה", "אין רשימות השמעה מותאמות אישית זמינות",
    "שמה של רשימת ההשמעה שונה בהצלחה", "הרצועה נוספה לרשימת ההשמעה בהצלחה", "הרצועה נמחקה מרשימת ההשמעה בהצלחה", "הוסף לתור", "הוסף הכל לתור",
    "נוסף לתור", "מיין תור", "שמור כרשימת השמעה", "נקה היסטוריה", "לנקות את כל הפריטים האחרונים?",
    "ההיסטוריה נוקתה", "אנא הכנס מונח לחיפוש", "הכנס מונח לחיפוש...", "תוצאות חיפוש", "לא נמצאו תוצאות",
    "מחפש: {0}", "סוג חיפוש", "להמשיך את ההפעלה האחרונה?", "איכות שמע", "עדכון אוטומטי",
    "בדוק עדכונים זמינים", "שמור הפעלה אחרונה", "אפשרויות", "ערכת נושא", "צבע ערכת הנושא",
    "Use Wi-Fi (Blackberry)", "טען תמונות ממוזערות", "כהה", "בהיר", "שיטת נגינה",
    "העבר InputStream", "העבר URL", "נתיב הורדה", "שמירת ההגדרות נכשלה", "שגיאה בשמירת ערכת הנושא: {0}",
    "שגיאה בטעינת ערכת הנושא: {0}", "עדכון צבע ערכת הנושא נכשל. מצב ערכת הנושא נשמר.", "Language/שפה", "בחר פריט להעביר, ואז בחר במיקום היעד", "הסידור נשמר",
    "שירות מוזיקה", "ההגדרות נשמרו בהצלחה", "בחר פריט להציג או להסתיר. [x] = מוצג, [] = מוסתר", "הגדרות הנראות נשמרו", "התרחשה שגיאה",
    "טוען...", "טען עוד...", "אין מידע זמין!", "אין עדכונים זמינים. ברשותך הגרסה העדכנית", "גרסה חדשה זמינה. לעדכן עכשיו?",
    "משך זמן חייב להיות בין 1 ל- 999", "פורמט זמן שגוי", "דקות", "פעולת קוצב זמן", "סגור אפליקציה",
    "עצור השמעה", "בטל קוצב זמן", "האפליקציה תסגר כאשר קוצב הזמן ייגמר. להמשיך?", "קבע קוצב זמן", "קוצב זמן לשינה",
    "קוצב זמן לשינה בוטל", "קוצב זמן לשינה סיים", "קוצב זמן לשינה הופעל", "Enable", "Presets",
    "Manual", "Band", "Equalizer is not supported on this device"
  };

  private static final String[] PL_VALS = {
    "pl", "Wróć", "Anuluj", "Wyjdź", "OK",
    "Zapisz", "MIDPlay", "Na pewno chcesz wyjść?", "Odrzucić niezapisane zmiany?", "Dodaj do ulubionych",
    "Nie udało się usunąć z ulubionych", "Nie udało się dodać do ulubionych", "Usuń z ulubionych", "Dodano do ulubionych", "Utwór już w ulubionych",
    "Usunięto z ulubionych", "Brak plików w tym folderze", "Nie jest plikiem audio", "Przejdź do katalogu głównego", "English",
    "Türkçe", "Tiếng Việt", "עברית", "Polski", "Português (Brasil)",
    "Album", "Playlista", "Utwór", "Odkrywaj playlisty", "Ulubione",
    "Teraz odtwarzane", "Ostatnie", "Pobrane", "Przeglądarka plików", "Przestaw menu",
    "Wyszukaj", "Ustawienia", "Więcej informacji", "Widoczność menu", "Korektor",
    "Następny", "Odtwórz", "Poprzedni", "Powtórz", "Pokaż playlisty",
    "Odtwarzanie losowe", "Ładowanie...", "Zatrzymano", "Odtwarzanie...", "Uruchamiam...",
    "Zatrzymano", "Zatrzymuję...", "Zakończono", "Gotowy", "Powtarzanie playlisty włączone",
    "Powtarzanie utworu włączone", "Powtarzanie wyłączone", "Losowe odtwarzanie playlisty włączone", "Losowe odtwarzanie playlisty wyłączone", "Zatrzymaj",
    "Głośność", "Szczegóły", "Nazwa", "Typ", "Własne",
    "System", "Ilość utworów", "Wykonawca", "Czas trwania", "URL",
    "Nieznany wykonawca", "Nieznany czas", "Brak URL", "Pobierz", "Pobieranie...",
    "Pobieranie zakończone", "Utwór został już pobrany", "Pobieranie już trwa", "Nie udało się pobrać: {0}", "Odtwórz",
    "Usuń", "Usuń wszystkie", "Odśwież", "Powiąż plik lokalny", "URL utworu",
    "URL miniatury", "Nazwa utworu", "Wykonawca", "Nie znaleziono plików lokalnych w folderze pobierania", "Podaj URL utworu",
    "Nie udało się powiązać tego pliku", "Plik powiązano pomyślnie", "Wpisz URL ręcznie", "Usunięto pobrany plik", "Usunięto wszystkie pobrane pliki",
    "Usunąć wszystkie pobrane utwory?", "Listen", "Delete", "Delete All", "Cached Songs",
    "Unknown Song", "Cached song removed", "Cache cleared", "Delete all cached songs?", "Dodaj do playlisty",
    "Utwórz playlistę", "Playlista nie jest pusta. Na pewno usunąć?", "Wyświetl listę utworów", "Nie udało się dodać utworu do playlisty", "Utwór już jest w playliście",
    "Nie można zmienić nazwy playlisty systemowej", "Nie udało się stworzyć playlisty", "Nazwa playlisty nie może być pusta", "Nie udało się usunąć utworu z playlisty", "Nie udało się zmienić nazwy",
    "Nazwa playlisty", "Zmień nazwę playlisty", "Wybierz playlistę", "Stworzono playlistę", "Brak własnych playlist",
    "Zmieniono nazwę", "Dodano utwór", "Usunięto utwór", "Dodaj do kolejki", "Dodaj wszystko do kolejki",
    "Dodano do kolejkę", "Sortuj kolejkę", "Zapisz jako playlistę", "Wyczyść historię", "Wyczyścić całą historię?",
    "Historia wyczyszczona", "Napisz co chcesz wyszukać", "Wyszukaj...", "Wyniki wyszukiwania", "Nic nie znaleziono",
    "Szukanie: {0}", "Typ wyszukiwania", "Wznowić ostatnią sesję?", "Jakość dźwięku", "Automatyczne aktualizacje",
    "Sprawdź aktualizacje", "Zapisz ostatnią sesję", "Opcje", "Wygląd", "Motyw",
    "Use Wi-Fi (Blackberry)", "Ładuj miniatury", "Ciemny", "Jasny", "Sposób odtwarzania",
    "Przekaż strumień wejściowy", "Przekaż URL", "Ścieżka pobierania", "Nie udało się załadować ustawień", "Błąd zapisywania motywu: {0}",
    "Błąd ładowania motywu: {0}", "Aktualizacja koloru motywu nie powiodła się. Zapisano tryb wyglądu.", "Język", "Najpierw wybierz ustawienie do przemieszczenia, następnie wybierz pozycję docelową", "Kolejność zapisana",
    "Usługa", "Zapisano", "Wybierz elementy do ukrycia/pokazania. [x] = pokaż, [] = ukryj", "Zapisano", "Wystąpił błąd",
    "Ładowanie...", "Załaduj więcej...", "Brak danych!", "Brak nowych aktualizacji. Masz najnowszą wersję", "Dostępna jest nowa wersja. Zaktualizować?",
    "Czas musi być w zakresie 1-999 minut", "Zły format czasu", "Minuty", "Funkcje minutnika", "Opuść aplikację",
    "Zatrzymaj odtwarzanie", "Zatrzymaj minutnik", "Minutnik zamknie aplikacje po określonym czasie, kontynuować?", "Ustaw minutnik", "Minutnik",
    "Odliczanie zatrzymane", "Koniec odliczania", "Aktywowano odliczanie", "Enable", "Presets",
    "Manual", "Band", "Equalizer is not supported on this device"
  };

  private static final String[] PT_VALS = {
    "pt", "Voltar", "Cancelar", "Sair", "OK",
    "Salvar", "MIDPlay", "Tem certeza que deseja sair?", "Descartar alterações não salvas?", "Adicionar aos Favoritos",
    "Falha ao remover dos favoritos", "Falha ao salvar nos favoritos", "Remover dos Favoritos", "Adicionado aos favoritos", "Já está nos favoritos",
    "Removido dos favoritos", "Nenhum arquivo nesta pasta", "Não é um arquivo de áudio", "Ir para a raiz", "English",
    "Türkçe", "Tiếng Việt", "עברית", "Polski", "Português (Brasil)",
    "Álbum", "Playlist", "Música", "Descobrir Playlists", "Favoritos",
    "Tocando Agora", "Recentes", "Downloads", "Explorador de Arquivos", "Reordenar Menu",
    "Pesquisar", "Configurações", "Sobre", "Visibilidade do Menu", "Equalizador",
    "Próxima", "Tocar", "Anterior", "Repetir", "Mostrar Playlist",
    "Embaralhar", "Carregando...", "Pausado", "Tocando...", "Iniciando...",
    "Parado", "Parando...", "Finalizado", "Pronto", "Repetir playlist ativado",
    "Repetir faixa ativado", "Repetir desativado", "Embaralhar playlist ativado", "Embaralhar playlist desativado", "Parar",
    "Volume", "Detalhes", "Nome", "Tipo", "Personalizado",
    "Sistema", "Número de Músicas", "Artista", "Duração", "URL",
    "Artista Desconhecido", "Duração Desconhecida", "Sem URL", "Baixar", "Baixando...",
    "Download concluído", "Música já baixada", "Download já em andamento", "Falha no download: {0}", "Tocar",
    "Excluir", "Excluir Tudo", "Atualizar", "Vincular local", "URL da música",
    "URL da capa", "Nome da música", "Artista", "Nenhum arquivo local encontrado na pasta de downloads", "Informe a URL da música",
    "Não foi possível vincular o arquivo", "Arquivo vinculado com sucesso", "Digitar URL manualmente", "Download excluído", "Todos os downloads foram excluídos",
    "Excluir todas as músicas baixadas?", "Ouvir", "Excluir", "Excluir tudo", "Músicas em cache",
    "Música desconhecida", "Música removida do cache", "Cache limpo", "Excluir todas as músicas em cache?", "Adicionar à Playlist",
    "Criar Playlist", "Esta playlist não está vazia. Excluir tudo?", "Ver Lista de Músicas", "Falha ao adicionar música à playlist", "A música já existe na playlist",
    "Não é possível renomear playlists do sistema", "Falha ao criar playlist", "O nome da playlist não pode ficar vazio", "Falha ao remover música da playlist", "Falha ao renomear playlist",
    "Nome da Playlist", "Renomear Playlist", "Selecionar Playlist", "Playlist criada com sucesso", "Nenhuma playlist personalizada disponível",
    "Playlist renomeada com sucesso", "Música adicionada à playlist com sucesso", "Música removida da playlist com sucesso", "Adicionar à Fila", "Adicionar Tudo à Fila",
    "Adicionado à fila", "Ordenar Fila", "Salvar como Playlist", "Limpar Histórico", "Limpar todos os itens recentes?",
    "Histórico limpo", "Digite uma palavra-chave para pesquisar", "Digite as palavras-chave para pesquisar...", "Resultados da Pesquisa", "Nenhum resultado encontrado",
    "Pesquisando por: {0}", "Tipo de Pesquisa", "Retomar sua última sessão?", "Qualidade de Áudio", "Atualizações Automáticas",
    "Verificar Atualizações", "Salvar Última Sessão", "Opções", "Aparência", "Cor do Tema",
    "Usar Wi-Fi (Blackberry)", "Carregar Miniaturas", "Escuro", "Claro", "Método do Player",
    "Passar InputStream", "Passar URL", "Caminho de Download", "Falha ao salvar configurações", "Erro ao salvar tema: {0}",
    "Erro ao carregar tema: {0}", "Falha na atualização da cor do tema. O modo do tema foi salvo.", "Idioma", "Selecione um item para mover e depois a posição de destino", "Ordem salva",
    "Serviço", "Configurações salvas com sucesso", "Selecione itens para ocultar/mostrar. [x] = mostrar, [] = ocultar", "Configurações de visibilidade salvas", "Ocorreu um erro",
    "Carregando...", "Carregar mais...", "Nenhum dado disponível!", "Nenhuma atualização disponível. Você está com a versão mais recente", "Nova versão disponível. Atualizar agora?",
    "A duração deve ser de 1 a 999 minutos", "Formato de hora inválido", "Minutos", "Ação do Temporizador", "Sair do Aplicativo",
    "Parar Reprodução", "Cancelar Temporizador", "O temporizador fechará o aplicativo quando expirar. Continuar?", "Definir Temporizador", "Temporizador de Suspensão",
    "Temporizador de suspensão cancelado", "Temporizador de suspensão expirou", "Temporizador de suspensão ativado", "Ativar", "Predefinições",
    "Manual", "Banda", "O equalizador não é suportado neste dispositivo"
  };

  private static final String[] TR_VALS = {
    "tr", "Geri", "İptal", "Çık", "Tamam",
    "Kaydet", "MIDPlay", "Çıkmak istediğinizden emin misiniz?", "Kaydedilmemiş değişiklikler silinsin mi?", "Favorilere Ekle",
    "Favori çıkarma hatası", "Favori kaydetme hatası", "Favorilerden Çıkar", "Favorilere eklendi", "Zaten favorilerde",
    "Favorilerden çıkarıldı", "Bu klasörde dosya yok", "Ses dosyası değil", "Köke git", "English",
    "Türkçe", "Tiếng Việt", "עברית", "Polski", "Português (Brasil)",
    "Albüm", "Çalma Listesi", "Şarkı", "Çalma Listelerini Keşfet", "Favoriler",
    "Şimdi Çalıyor", "Son çalınanlar", "İndirilenler", "Dosya Gezgini", "Menüyü Yeniden Sırala",
    "Arama", "Ayarlar", "Hakkında", "Menü Görünürlüğü", "Ekolayzır",
    "Sonraki", "Çal", "Önceki", "Tekrarla", "Çalma Listesini Göster",
    "Karıştır", "Yükleniyor...", "Duraklatıldı", "Çalıyor...", "Başlatılıyor...",
    "Durduruldu", "Durduruluyor...", "Tamamlandı", "Hazır", "Oynatma listesi tekrarı açık",
    "Parça tekrarı açık", "Tekrar kapalı", "Oynatma listesi karıştırma açık", "Oynatma listesi karıştırma kapalı", "Durdur",
    "Ses", "Detaylar", "Ad", "Tür", "Özel",
    "Sistem", "Şarkı Sayısı", "Sanatçı", "Süre", "URL",
    "Bilinmeyen Sanatçı", "Bilinmeyen Süre", "URL yok", "İndir", "İndiriliyor...",
    "İndirme tamamlandı", "Şarkı zaten indirildi", "İndirme zaten devam ediyor", "İndirme başarısız: {0}", "Çal",
    "Sil", "Tümünü Sil", "Yenile", "Yerel Dosyayı Bağla", "Şarkı URL",
    "Küçük resim URL", "Şarkı Adı", "Sanatçı", "İndirme klasöründe yerel dosya bulunamadı", "Lütfen şarkı URL girin",
    "Bu dosya bağlanamadı", "Dosya başarıyla bağlandı", "URL'yi elle gir", "İndirme silindi", "Tüm indirmeler silindi",
    "İndirilen tüm şarkılar silinsin mi?", "Listen", "Delete", "Delete All", "Cached Songs",
    "Unknown Song", "Cached song removed", "Cache cleared", "Delete all cached songs?", "Çalma Listesine Ekle",
    "Çalma Listesi Oluştur", "Bu çalma listesinde şarkılar var. Çalma listesini ve tüm şarkıları sil?", "Şarkı Listesini Görüntüle", "Şarkı çalma listesine eklenemedi", "Şarkı zaten çalma listesinde mevcut",
    "Sistem çalma listesi yeniden adlandırılamaz", "Çalma listesi oluşturulamadı", "Çalma listesi adı boş olamaz", "Şarkı çalma listesinden çıkarılamadı", "Çalma listesi yeniden adlandırılamadı",
    "Çalma Listesi Adı", "Çalma Listesini Yeniden Adlandır", "Çalma Listesi Seç", "Çalma listesi başarıyla oluşturuldu", "Özel çalma listesi yok",
    "Çalma listesi başarıyla yeniden adlandırıldı", "Şarkı çalma listesine eklendi", "Şarkı çalma listesinden çıkarıldı", "Sıraya ekle", "Tümünü sıraya ekle",
    "Sıraya eklendi", "Sırala", "Çalma listesi olarak kaydet", "Geçmişi Temizle", "Tüm son çalınanlar silinsin mi?",
    "Geçmiş temizlendi", "Lütfen arama için bir anahtar kelime girin", "Arama için anahtar kelime girin...", "Arama Sonuçları", "Sonuç bulunamadı",
    "Aranan: {0}", "Arama Türü", "Son oturumunuza devam edilsin mi?", "Ses Kalitesi", "Otomatik Güncellemeler",
    "Güncellemeleri Kontrol Et", "Son Oturumu Kaydet", "Seçenekler", "Tema Modu", "Tema Rengi",
    "Wi-Fi kullan (Blackberry)", "Küçük Resimleri Yükle", "Koyu", "Açık", "Oynatıcı Yöntemi",
    "InputStream Geçir", "URL Geçir", "İndirme Yolu", "Ayarlar kaydedilemedi", "Tema kaydedilirken hata: {0}",
    "Tema yüklenirken hata: {0}", "Tema rengi güncellenemedi. Tema modu kaydedildi.", "Dil", "Taşınacak öğeyi seçin, sonra hedef konumu seçin", "Sıralama kaydedildi",
    "Servis", "Ayarlar başarıyla kaydedildi", "Gizlenecek/gösterilecek öğeleri seçin. [x] = göster, [] = gizle", "Görünürlük ayarları kaydedildi", "Bir hata oluştu",
    "Yükleniyor...", "Daha fazla yükle...", "Veri yok!", "Güncelleme yok. En son sürümü kullanıyorsunuz", "Yeni sürüm mevcut. Şimdi güncellensin mi?",
    "Süre 1-999 dakika arasında olmalı", "Geçersiz zaman formatı", "Dakika", "Zamanlayıcı Eylemi", "Uygulamadan Çık",
    "Çalmayı Durdur", "Zamanlayıcıyı İptal Et", "Zamanlayıcı süresi dolduğunda uygulamadan çıkacak. Devam et?", "Zamanlayıcı Ayarla", "Uyku Zamanlayıcısı",
    "Uyku zamanlayıcısı iptal edildi", "Uyku zamanlayıcısı süresi doldu", "Uyku zamanlayıcısı etkinleştirildi", "Aktif", "Öntanımlı ayarlar",
    "Manuel", "Band", "Ekolayzır bu cihazda desteklenmiyor"
  };

  private static final String[] VI_VALS = {
    "vi", "Quay lại", "Hủy", "Thoát", "OK",
    "Lưu", "MIDPlay", "Bạn có chắc chắn muốn thoát?", "Hủy các thay đổi chưa lưu?", "Thêm vào yêu thích",
    "Không thể xóa khỏi mục yêu thích", "Không thể lưu vào mục yêu thích", "Xóa khỏi yêu thích", "Đã thêm vào yêu thích", "Bài hát đã có trong mục yêu thích",
    "Đã xóa khỏi yêu thích", "Không có tệp nào trong thư mục này", "Không phải tệp âm thanh", "Đi đến thư mục gốc", "English",
    "Türkçe", "Tiếng Việt", "עברית", "Polski", "Português (Brasil)",
    "Album", "Playlist", "Bài hát", "Khám phá playlist", "Yêu thích",
    "Đang phát", "Gần đây", "Đã tải xuống", "Trình duyệt tệp", "Sắp xếp menu",
    "Tìm kiếm", "Cài đặt", "Giới thiệu", "Ẩn/hiện menu", "Bộ chỉnh âm",
    "Bài tiếp theo", "Phát", "Bài trước", "Lặp lại", "Xem playlist",
    "Phát ngẫu nhiên", "Đang tải...", "Đã tạm dừng", "Đang phát...", "Đang chuẩn bị...",
    "Đã dừng", "Đang dừng...", "Đã phát xong", "Sẵn sàng", "Đã bật lặp lại danh sách phát",
    "Đã bật lặp lại bài hát", "Đã tắt lặp lại", "Đã bật phát ngẫu nhiên danh sách phát", "Đã tắt phát ngẫu nhiên danh sách phát", "Dừng",
    "Âm lượng", "Chi tiết", "Tên", "Loại", "Tùy chỉnh",
    "Hệ thống", "Số lượng bài hát", "Nghệ sĩ", "Thời lượng", "Liên kết",
    "Không rõ nghệ sĩ", "Không rõ thời lượng", "Không có liên kết", "Tải xuống", "Đang tải xuống...",
    "Tải xuống hoàn tất", "Bài hát đã được tải xuống", "Đang tải xuống rồi", "Tải xuống thất bại: {0}", "Phát",
    "Xóa", "Xóa tất cả", "Làm mới", "Liên kết tệp cục bộ", "URL bài hát",
    "URL hình thu nhỏ", "Tên bài hát", "Nghệ sĩ", "Không tìm thấy tệp cục bộ trong thư mục tải xuống", "Vui lòng nhập URL bài hát",
    "Không thể liên kết tệp này", "Liên kết tệp thành công", "Nhập URL thủ công", "Đã xóa bản tải xuống", "Đã xóa toàn bộ bản tải xuống",
    "Xóa tất cả bài hát đã tải xuống?", "Listen", "Delete", "Delete All", "Cached Songs",
    "Unknown Song", "Cached song removed", "Cache cleared", "Delete all cached songs?", "Thêm vào playlist",
    "Tạo playlist", "Playlist này có chứa bài hát. Bạn vẫn muốn xóa?", "Xem các bài hát", "Không thể thêm bài hát vào playlist", "Bài hát đã có trong playlist",
    "Không thể đổi tên playlist hệ thống", "Không thể tạo playlist", "Tên playlist không được để trống", "Không thể xóa bài hát khỏi playlist", "Không thể đổi tên playlist",
    "Tên playlist", "Đổi tên playlist", "Chọn playlist", "Tạo playlist thành công", "Chưa có playlist tự tạo",
    "Đổi tên playlist thành công", "Đã thêm bài hát vào playlist", "Đã xóa bài hát khỏi playlist", "Thêm vào hàng đợi", "Thêm tất cả vào hàng đợi",
    "Đã thêm vào hàng đợi", "Sắp xếp hàng đợi", "Lưu thành playlist", "Xóa danh sách gần đây", "Xóa toàn bộ mục gần đây?",
    "Đã xóa danh sách gần đây", "Vui lòng nhập từ khóa tìm kiếm", "Tìm kiếm bài hát, nghệ sĩ, playlist...", "Kết quả tìm kiếm", "Không tìm thấy kết quả",
    "Đang tìm kiếm: {0}", "Bộ lọc tìm kiếm", "Tiếp tục phát phiên gần nhất?", "Chất lượng âm thanh", "Tự động cập nhật",
    "Kiểm tra cập nhật", "Lưu phiên nghe cuối cùng", "Tùy chọn", "Chế độ giao diện", "Màu chủ đề",
    "Dùng Wi-Fi (Blackberry)", "Hiển thị ảnh thu nhỏ", "Tối", "Sáng", "Phương thức phát",
    "Truyền InputStream", "Truyền URL", "Đường dẫn tải xuống", "Không thể lưu cài đặt", "Lỗi lưu giao diện: {0}",
    "Lỗi tải giao diện: {0}", "Không thể cập nhật màu nền. Đã lưu chế độ giao diện.", "Ngôn ngữ", "Chọn mục để di chuyển, sau đó chọn vị trí mới", "Đã lưu thứ tự",
    "Dịch vụ", "Lưu cài đặt thành công", "Chọn mục để ẩn hoặc hiện. [x] = Hiện, [] = Ẩn", "Đã lưu cài đặt hiển thị", "Đã xảy ra lỗi",
    "Đang tải...", "Tải thêm...", "Không có dữ liệu", "Bạn đang sử dụng phiên bản mới nhất", "Có phiên bản mới. Cập nhật ngay?",
    "Thời lượng phải từ 1 đến 999 phút", "Định dạng thời gian không hợp lệ", "Phút", "Khi hết thời gian", "Thoát ứng dụng",
    "Dừng phát nhạc", "Hủy hẹn giờ", "Ứng dụng sẽ tự động thoát khi hết giờ. Tiếp tục?", "Đặt hẹn giờ", "Hẹn giờ tắt",
    "Đã hủy hẹn giờ tắt", "Đã hết thời gian hẹn giờ tắt", "Đã đặt hẹn giờ tắt", "Bật", "Cài đặt sẵn",
    "Tùy chỉnh", "Dải tần", "Thiết bị không hỗ trợ bộ chỉnh âm"
  };

  private static void l(String code) {
    if (d == null) {
      d = new Hashtable();
    } else {
      d.clear();
    }
    String[] vals = EN_VALS;
    if ("he".equals(code)) {
      vals = HE_VALS;
    }
    if ("pl".equals(code)) {
      vals = PL_VALS;
    }
    if ("pt".equals(code)) {
      vals = PT_VALS;
    }
    if ("tr".equals(code)) {
      vals = TR_VALS;
    }
    if ("vi".equals(code)) {
      vals = VI_VALS;
    }
    for (int j = 0; j < KEYS.length; j++) {
      d.put(KEYS[j], vals[j]);
    }
  }

  public static void setLang(String code) {
    if (!code.equals(c)) {
      c = code;
      l(code);
      i = true;
    }
  }

  public static String getCurrentLang() { return c; }

  public static String[] getAvailableLanguages() {
    return new String[] {"en", "he", "pl", "pt", "tr", "vi"};
  }

  public static String tr(String k) {
    if (!i) {
      l(c);
      i = true;
    }
    String v = (String) d.get(k);
    return v != null ? v : k;
  }

  public static String tr(String k, String a) {
    return Utils.replace(tr(k), "{0}", a);
  }

  private Lang() {}
}